services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Localizationteam\Localizer\:
    resource: '../Classes/*'

  Localizationteam\Localizer\Handler\FileDownloader:
    public: true

  Localizationteam\Localizer\Handler\FileImporter:
    public: true
